---
- name: Ensure dependency is installed (Ubuntu).
  apt: name=apt-transport-https state=present

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: kibana_version|int >= 6

- name: Add Kibana repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ kibana_version }}/apt stable main'
    state: present
    update_cache: yes
  when: kibana_version|int >= 6

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://packages.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: kibana_version|int < 6

- name: Add Kibana repository.
  apt_repository:
    repo: 'deb https://packages.elastic.co/kibana/{{ kibana_version }}/debian stable main'
    state: present
    update_cache: yes
  when: kibana_version|int < 6
